fixVariablesBug
matwjablonski/wdp-2305-01 pull request #11
Opened 2023-05-18 19:20 UTC by DawSeg

2023-05-18 21:01 UTC, LukaszLewandowski91 approved these changes
Super :)

2023-05-18 21:04 UTC, LukaszLewandowski91 approved these changes

2023-05-18 21:10 UTC, monte-dev requested changes
Wszystko wygląda okej, podrzuć może link do tego PR na czacie bo od tej pory każdy będzie musiał się trzymać tych nowych zmiennych :) A no i Mateusz mówił żebyśmy nazywali PR np [WDP230501-8] Bug Fix - Fix variables

2023-05-19 14:28 UTC, matwjablonski commented
proszę zmień tytuł i opis, nie bardzo wiem czego to dotyczy

dodatkowo masz konflikty

2023-05-22 08:15 UTC, matwjablonski requested changes

2023-05-22 08:15 UTC, matwjablonski commented on src/styles/settings.scss
> +$primary: $darkOrange;
masz dwa style pisania zmiennych:

kebab-case oraz camelCase

zdecyduj się proszę na jeden i uspójnij

2023-05-24 05:34 UTC, matwjablonski approved these changes

2023-05-24 05:36 UTC, merged