[ wdp230501-18] Change RWD for fotter
matwjablonski/wdp-2305-01 pull request #15
Opened 2023-05-19 12:14 UTC by Stolkens

zmieniłem ilość linkow  w kolumnach w zaleznosci od wielkosci ekranu, oraz rozmieszczenie tresci w  stopce

2023-05-19 21:34 UTC, LukaszLewandowski91 approved these changes

2023-05-20 14:42 UTC, DawSeg approved these changes

2023-05-20 14:42 UTC, DawSeg approved these changes

2023-05-22 09:13 UTC, matwjablonski requested changes

2023-05-22 09:13 UTC, matwjablonski commented on src/components/layout/Footer/Footer.js
>              <p>©Copyright 2016 Bazar | All Rights Reserved</p>
na wersji mobilnej ten tekst powinien być wyrównany do lewej zgodnie z resztą tekstów w stopce

2023-05-22 11:06 UTC, Stolkens commented on src/components/layout/Footer/Footer.js
>              <p>©Copyright 2016 Bazar | All Rights Reserved</p>
poprawione

2023-05-22 16:24 UTC, JL9696 approved these changes

2023-05-22 16:44 UTC, monte-dev approved these changes

2023-05-23 07:31 UTC, merged