[WDP2530501-10] Drop-down selection of categories in the search
matwjablonski/wdp-2305-01 pull request #18
Opened 2023-05-19 19:01 UTC by JL9696

2023-05-19 21:42 UTC, LukaszLewandowski91 requested changes
Przy li ustaw style-list-type na "none" oraz wyrównaj do lewej. Dodatkowo jak najedziesz to tło listy nie wygląda zbyt dobrze

2023-05-22 09:05 UTC, matwjablonski requested changes
@JL9696 brakuje opisu zadania i linku do zadania w JIRA w opisie

2023-05-22 09:07 UTC, matwjablonski requested changes

2023-05-22 09:07 UTC, matwjablonski commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +  .category:hover{
spacje przed `{`

2023-05-22 09:07 UTC, matwjablonski commented on src/components/features/ProductSearch/ProductSearch.js
> +    <form action='' className={styles.root}>
`action` jest zbędne, w zasadzie po co nam ten form tutaj?

2023-05-23 18:02 UTC, JL9696 commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +  .category:hover{
Zrobione

2023-05-23 18:03 UTC, JL9696 commented on src/components/features/ProductSearch/ProductSearch.js
> +    <form action='' className={styles.root}>
Zrobione

2023-05-23 18:25 UTC, monte-dev approved these changes

2023-05-24 05:40 UTC, matwjablonski requested changes

2023-05-24 05:40 UTC, matwjablonski commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +      background-color: white;
1. kolory mamy w zmiennych
2. nie jest dobrą praktyką używanie nazw kolorów

2023-05-24 05:40 UTC, matwjablonski commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +      padding: 0px 0px 0px 10px;
jak 0 to bez jednostki

2023-05-24 05:40 UTC, matwjablonski commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +    background-color: white;
jak wyżej

2023-05-24 05:40 UTC, matwjablonski commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +
jedna pusta linia pomiędzy regułami, dwie to już za dużo

2023-05-25 16:21 UTC, JL9696 commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +      background-color: white;
Zrobione

2023-05-25 16:21 UTC, JL9696 commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +      padding: 0px 0px 0px 10px;
Zrobione

2023-05-25 16:21 UTC, JL9696 commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +    background-color: white;
Zrobione

2023-05-25 16:21 UTC, JL9696 commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +
Zrobione

2023-05-25 17:06 UTC, LukaszLewandowski91 approved these changes

2023-05-25 23:39 UTC, Stolkens approved these changes

2023-05-26 08:29 UTC, matwjablonski approved these changes

2023-05-26 08:29 UTC, merged