[WDP230501-5] Dodano style na przyciski Ulubione i porównanie
matwjablonski/wdp-2305-01 pull request #21
Opened 2023-05-20 07:40 UTC by LukaszLewandowski91

Added styling for favorite and compare buttons. In initialState add favorite and comparison for all products and set true for selected products
https://projects.kodilla.com/browse/WDP230501-5

2023-05-20 20:25 UTC, monte-dev requested changes
"Po otwarciu strony ma być co najmniej po jednym produkcie, który ma aktywne: 

żaden z tych buttonów
tylko "ulubiony"
tylko "dodany do porównania"
oba buttony"

Ustawiles tylko favorite dla dwóch produktów

2023-05-22 09:50 UTC, LukaszLewandowski91 commented
> "Po otwarciu strony ma być co najmniej po jednym produkcie, który ma aktywne:
> 
> żaden z tych buttonów tylko "ulubiony" tylko "dodany do porównania" oba buttony"
> 
> Ustawiles tylko favorite dla dwóch produktów

Poprawione

2023-05-22 09:52 UTC, LukaszLewandowski91 reviewed
Poprawione

2023-05-22 10:31 UTC, Stolkens approved these changes

2023-05-22 11:35 UTC, monte-dev approved these changes

2023-05-23 07:41 UTC, merged