[WDP230501-12] Add component Sticky Bar
matwjablonski/wdp-2305-01 pull request #23
Opened 2023-05-20 08:41 UTC by LukaszLewandowski91

Dodano komponent StickyBar, który wyświetla aktualnie porównywane produkty. Każdy produkt na stickyBar zawiera miniaturkę zdjęcia, a po najechaniu kursorem na produkt pojawia się przycisk umożliwiający usunięcie produktu z porównania. Na prawo od listy porównywanych produktów pojawia się przycisk z ikoną "porównaj", który aktualnie jest nieaktywny.
https://projects.kodilla.com/browse/WDP230501-12

2023-05-20 18:15 UTC, JL9696 approved these changes

2023-05-22 09:01 UTC, matwjablonski requested changes

2023-05-22 09:01 UTC, matwjablonski commented on src/components/common/ProductBox/ProductBox.js
> +          <Button
jeśli mamy już max ilość w porównywarce dobrze żeby ten przycisk był wyszarzony (disabled)

2023-05-22 17:28 UTC, LukaszLewandowski91 commented on src/components/common/ProductBox/ProductBox.module.scss
> +    color: #ffffff;
Poprawione :)

2023-05-22 17:28 UTC, LukaszLewandowski91 commented on src/components/common/ProductBox/ProductBox.js
> +          <Button
Dodano wyszarzenie gdy osiągnięto limit produktów w porównaniu.

2023-05-22 18:24 UTC, monte-dev approved these changes

2023-05-23 09:06 UTC, matwjablonski commented
@LukaszLewandowski91 konflikty :)

2023-05-23 09:14 UTC, LukaszLewandowski91 commented
> @LukaszLewandowski91 konflikty :)

Konflikty rozwiązane.

2023-05-23 09:15 UTC, matwjablonski commented
> > @LukaszLewandowski91 konflikty :)
> 
> Konflikty rozwiązane.

Spoko, ale masz jeszcze komentarz od @monte-dev  ;)

2023-05-23 16:34 UTC, LukaszLewandowski91 commented
> Jeszcze tylko tą drobną rzecz można poprawić w zadaniu jest: "Na hover na zdjęciu ma się pojawiać ikona zamykania, a kliknięcie zdjęcie usuwa ten produkt z porównania)" a obecnie usunąc produkt można przez klik na ikone a nie zdjęcie. A chyba chodzi o user experience bo zdj małe to i button mały :p,

Poprawione :)

2023-05-23 16:34 UTC, LukaszLewandowski91 commented
> > > @LukaszLewandowski91 konflikty :)
> > 
> > 
> > Konflikty rozwiązane.
> 
> Spoko, ale masz jeszcze komentarz od @monte-dev ;)

Zmiana wprowadzona :)

2023-05-24 09:50 UTC, Stolkens approved these changes

2023-05-26 08:32 UTC, matwjablonski approved these changes

2023-05-26 08:32 UTC, merged