[WDP230501-21] - dodano komponent z oceną użytkownika
matwjablonski/wdp-2305-01 pull request #25
Opened 2023-05-21 11:23 UTC by LukaszLewandowski91

Wydzielono komponent z oceną użytkownika. 
Średnia ocena wyświetlana jest jako czarna gwiazdka ale gdy użytkownik doda swoją ocenę to ocena użytkownika zyskuje priorytet i wyświetlana jest w kolorze kremowym. 
Efekt hover zmienia typ ikony gwiazdki z farStar na faStar z kremowym wypełnieniem.
Ocena użytkownika zapisuje się w stanie aplikacji.
https://projects.kodilla.com/browse/WDP230501-21

2023-05-21 16:51 UTC, monte-dev commented
Jak zaznacze np 4 gwiazdki, i później hoveruje na 1 gwiazdke to gwiazdki 2,3,4 są na czarno, tak jakby ocena 4 była średnią

2023-05-21 18:19 UTC, LukaszLewandowski91 commented
> Jak zaznacze np 4 gwiazdki, i później hoveruje na 1 gwiazdke to gwiazdki 2,3,4 są na czarno, tak jakby ocena 4 była średnią

Poprawione :)

2023-05-22 08:53 UTC, matwjablonski requested changes

2023-05-22 08:53 UTC, matwjablonski commented on src/components/features/RatingStars/RatingStars.js
> +  const [ratingOption, setRatingOption] = useState('');
dałeś wartość domyślną jako pusty string, a w zasadzie zamiast warunku w useEffect możesz tutaj przypisać ten stan

2023-05-22 08:53 UTC, matwjablonski commented on src/components/features/RatingStars/RatingStars.js
> +    rating === 0 || rating === undefined
nie widzę funkcjonalności żeby rating miał wartość 0?

2023-05-22 18:12 UTC, LukaszLewandowski91 commented on src/components/features/RatingStars/RatingStars.js
> +  const [ratingOption, setRatingOption] = useState('');
Ustawiono stan jako domyślną wartość

2023-05-22 18:14 UTC, LukaszLewandowski91 commented on src/components/features/RatingStars/RatingStars.js
> +    rating === 0 || rating === undefined
Wprowadziłem funkcjonalność anulowania swojego wyboru co jest równoznaczne z wartością 0. Gdy użytkownik kliknie np. 3 gwiazdki i będzie chciał anulować swój wybór to ponowne kliknięcie 3 gwiazdek ustawi jego wybór na 0 i przywróci średnią ocenę

2023-05-22 18:17 UTC, monte-dev approved these changes

2023-05-23 09:46 UTC, LukaszLewandowski91 reviewed
Konflikty rozwiązane

2023-05-24 05:41 UTC, matwjablonski approved these changes

2023-05-24 05:41 UTC, merged