Wdp230501 2
matwjablonski/wdp-2305-01 pull request #3
Opened 2023-05-17 12:06 UTC by Stolkens

fix styles in cartCounter

2023-05-19 13:48 UTC, monte-dev approved these changes

2023-05-19 14:17 UTC, matwjablonski requested changes

2023-05-19 14:17 UTC, matwjablonski commented on src/components/common/ProductBox/ProductBox.js
> +      {<img key={image} src={image} alt='furniture' />}
każdy produkt będzie miał ten sam alt?

2023-05-19 14:19 UTC, matwjablonski commented
<img width="125" alt="Zrzut ekranu 2023-05-19 o 16 18 45" src="https://github.com/matwjablonski/wdp-2305-01/assets/20933197/1c380b3c-da98-4972-a7ca-321717b9b497">

przy dużej wartości liczby są za blisko krawędzi

2023-05-20 14:10 UTC, Stolkens commented on src/components/common/ProductBox/ProductBox.js
> +      {<img key={image} src={image} alt='furniture' />}
> każdy produkt będzie miał ten sam alt?

no w sumie racja, już zmieniam

2023-05-20 14:11 UTC, Stolkens commented on src/components/common/ProductBox/ProductBox.js
> +      {<img key={image} src={image} alt='furniture' />}
> w jakim celu image ma key?

myślałem, że key musi być zawsze

2023-05-20 14:15 UTC, Stolkens commented on src/components/common/ProductBox/ProductBox.module.scss
> +    padding: 0 0 0 0;
> wystarczy jedno 0

ok

2023-05-21 20:03 UTC, Stolkens commented
> <img alt="Zrzut ekranu 2023-05-19 o 16 18 45" width="125" src="https://user-images.githubusercontent.com/20933197/239556746-1c380b3c-da98-4972-a7ca-321717b9b497.png">
> przy dużej wartości liczby są za blisko krawędzi

- dodałem padding - myślę, że wygląda ok

2023-05-23 21:24 UTC, Stolkens commented
> @Stolkens gdzie dodałeś ten padding - nie widzę żadnego commita nowego tutaj?

przez przypadek stworzyłem go na nowym branchu....stworzyłem nowy PR

2023-05-24 05:59 UTC, matwjablonski commented
> > @Stolkens gdzie dodałeś ten padding - nie widzę żadnego commita nowego tutaj?
> 
> przez przypadek stworzyłem go na nowym branchu....stworzyłem nowy PR

spoko, ale musi być tutaj, więc wprowadź tę zmianę do tego brancha :)

2023-05-24 06:25 UTC, Stolkens commented
> > > @Stolkens gdzie dodałeś ten padding - nie widzę żadnego commita nowego tutaj?
> > 
> > 
> > przez przypadek stworzyłem go na nowym branchu....stworzyłem nowy PR
> 
> spoko, ale musi być tutaj, więc wprowadź tę zmianę do tego brancha :)

no, chyba w końcu się udało:)

2023-05-25 09:18 UTC, matwjablonski commented
ostatni commit jest z 21 maja

pytanko: czemu na tym branchu są też rzeczy związane z ProductBox? to chyba nie było związane z tym zadaniem, prawda?

2023-05-25 09:32 UTC, closed without merging

2023-05-25 10:10 UTC, Stolkens commented
> ostatni commit jest z 21 maja
> 
> pytanko: czemu na tym branchu są też rzeczy związane z ProductBox? to chyba nie było związane z tym zadaniem, prawda?

 No nie było, pomyłka przy przełączaniu branchy ;/