[Wdp 230501 33] Add ClientFeedback component
matwjablonski/wdp-2305-01 pull request #37
Opened 2023-05-24 00:08 UTC by Stolkens

- dodałem komponent ClientFeedback
- dodałem treści, które są pobierane  z InitialState
- ostylowane według wzoru z taska

https://projects.kodilla.com/browse/WDP230501-33

2023-05-24 05:28 UTC, LukaszLewandowski91 requested changes
Kilka uwag w stylach komponentu ClientFeedback :)

2023-05-24 05:28 UTC, LukaszLewandowski91 commented on src/components/features/ClientFeedback/ClientFeedback.module.scss
> +      border-bottom: 4px solid #e2e2e2;
Warto dodać kolor do settings lub wykorzystać jeżeli taki istnieje :)

2023-05-24 05:28 UTC, LukaszLewandowski91 commented on src/components/features/ClientFeedback/ClientFeedback.module.scss
> +        background-color: #ffffff;
Tutaj podobnie, w jednym z commitów dodawałem ten kolor do settings jako $text-color-light (jeszcze nie jest mergowany)

2023-05-24 05:28 UTC, LukaszLewandowski91 commented on src/components/features/ClientFeedback/ClientFeedback.module.scss
> +            background-color: #e1e1e1;
To samo :) Dodaj kolor do settings :)

2023-05-24 06:20 UTC, Stolkens commented on src/components/features/ClientFeedback/ClientFeedback.module.scss
> +      border-bottom: 4px solid #e2e2e2;
zrobione

2023-05-24 06:20 UTC, Stolkens commented on src/components/features/ClientFeedback/ClientFeedback.module.scss
> +        background-color: #ffffff;
zrobione

2023-05-24 06:42 UTC, LukaszLewandowski91 commented on src/components/features/ClientFeedback/ClientFeedback.module.scss
> +            background-color: #e1e1e1;
A wysłałeś commit ?

2023-05-24 06:50 UTC, Stolkens commented on src/components/features/ClientFeedback/ClientFeedback.module.scss
> +            background-color: #e1e1e1;
tak , jest poniżej

2023-05-26 08:34 UTC, matwjablonski approved these changes

2023-05-26 08:35 UTC, merged