Wdp230501 4
matwjablonski/wdp-2305-01 pull request #4
Opened 2023-05-17 14:50 UTC by LukaszLewandowski91

Hide buttons "Quick View" and "Add to Cart" . When the cursor is on the product box then buttons are visible and button price changes background color
https://projects.kodilla.com/browse/WDP230501-4

2023-05-18 11:40 UTC, Stolkens requested changes
Na tym branchu wprowadzone są również zmiany z WDP230501-3

2023-05-18 15:50 UTC, LukaszLewandowski91 commented
> Na tym branchu wprowadzone są również zmiany z WDP230501-3

Zapomniałem sie przełączyć pomiędzy branchami :/

2023-05-18 16:26 UTC, LukaszLewandowski91 reviewed
Nie zmieniłem brancha przez co nadpisał się również inny commit

2023-05-19 05:47 UTC, Stolkens approved these changes

2023-05-19 13:58 UTC, monte-dev reviewed
Najezdzajac na karte produktu, div z 'quick view' i ' add to cart' wciska sie pomiedzy dwa inne divy przez co efekt mamy taki ze jedna karta produktu jest wieksza niz inne i wszystko wyglada jakby skakało, taki pomysł aby może zrobić div z 'quick view i add to cart' nachodzacy na obrazek? i moze lekko opacity zmodyfikowane.

2023-05-19 20:49 UTC, closed without merging