[WDP230501-24] add promotion RWD
matwjablonski/wdp-2305-01 pull request #48
Opened 2023-05-28 13:13 UTC by JL9696

- ukryłam lewy slider „hot deal”,
- ustawiłam prawy na całą szerokość containera,
- dodałam Swipeable

https://projects.kodilla.com/browse/WDP230501-24

2023-05-28 15:32 UTC, monte-dev requested changes

2023-05-28 15:32 UTC, monte-dev commented on src/components/features/Promoted/PromotedProducts.js
> +  const handleSwipeRight = () => {
Tutaj potrzeba dodac funkcje ktora Swipeable ma uruchomic. W NewFurniture masz przyklad, bo innaczej to Swipeable, nie wie co ma zmienic.

2023-05-28 15:32 UTC, monte-dev commented on src/components/features/Promoted/PromotedProducts.js
> +              <Button className={styles.arr_right}>
Wszystkie elementy w swipeable musza byc elementami ktore maja sie zmieniac "slajdami". Buttony i reszta powinna byc na zewnatrz kontenera Swipeable. Wsrodku swipeable powinny byc np, albo same obrazki ktore sie zmieniaja, albo komponenty. W sekcji customerfeedback ktora zrobil Lukasz mozesz podejrzec.

2023-05-28 15:32 UTC, monte-dev commented on src/components/features/Promoted/PromotedProducts.module.scss
>    h3{
brak spacji w kilku miejscach

2023-05-28 15:32 UTC, monte-dev commented on src/components/features/Promoted/PromotedProducts.module.scss
> +    padding-right: 0 !important;
Gdy dodasz takie style do max-width 991px to nie musisz to tego media query jeszcze raz

2023-05-28 15:32 UTC, monte-dev commented on src/components/features/Promoted/PromotedProducts.module.scss
> +    margin-top: 0 !important;
bez important sie obejdzie

2023-05-28 21:33 UTC, matwjablonski commented on src/components/features/Promoted/PromotedProducts.module.scss
> +    padding-right: 0 !important;
!importanty są ostatecznością, w takiej postaci nie może to być zaakceptowane - popracuj specyficznością

2023-05-31 09:17 UTC, matwjablonski approved these changes

2023-05-31 13:19 UTC, Stolkens approved these changes

2023-05-31 15:37 UTC, merged