add-sales-component-and-styles
matwjablonski/wdp-2305-01 pull request #49
Opened 2023-05-28 19:17 UTC by DawSeg

Jeden z obrazów jest trochę nie wyjściowy, ale swoją rolę spełnia.

2023-05-29 04:36 UTC, LukaszLewandowski91 commented
![image](https://github.com/matwjablonski/wdp-2305-01/assets/119667464/75f257b4-cad4-40cc-bf61-35296334b9e0)
Ten obrazek przysłania napis, typ pliku obrazka na png powinien lepiej prezentować się w komponencie :)

2023-05-29 16:13 UTC, monte-dev requested changes

2023-05-29 16:13 UTC, monte-dev commented on src/components/features/Sales/Sales.js
> +              </div>
ten div jakbys mogl dac kilka lini nizej, do tego samego diva w ktorym jest obrazek. Wtedy bedzie latwiej Ci tez to zpozycjonowac

2023-05-29 16:13 UTC, monte-dev commented on src/components/features/Sales/Sales.js
> +      <div className={`${styles.leftSide} col-6`}>
Uzywasz klasy leftSide, ale w scss takiej nie widze

2023-05-30 07:25 UTC, Stolkens commented on src/components/features/Sales/Sales.js
> +              </div>
Dokładnie jak pisze monte-dev. Bo w tej chwili masz opis dolnego obrazka w divie górnego

2023-05-30 16:34 UTC, JL9696 approved these changes

2023-05-30 17:56 UTC, closed without merging