[Wdp230501 37] Add Cart
matwjablonski/wdp-2305-01 pull request #59
Opened 2023-05-31 11:19 UTC by Stolkens

- dodałem komponent Cart
- dodałem możliwośc dodawania produktów do koszyka z poziomu produktów i galerii
- koszyk otwiera pokazuje ilość produktów , rodzaje i ich ilość, cenę , przesyłkę oraz wartość całkowitą
- ostylowane (autor bez zmysłu estetycznego :)

https://projects.kodilla.com/browse/WDP230501-37

2023-05-31 12:11 UTC, JL9696 approved these changes

2023-05-31 12:48 UTC, LukaszLewandowski91 requested changes

2023-05-31 12:48 UTC, LukaszLewandowski91 commented on src/components/features/Cart/Cart.module.scss
> +    background-color: #d58f34;
Dodaj proszę kolor do settings :)

2023-05-31 13:57 UTC, Stolkens commented on src/components/features/Cart/Cart.module.scss
> +    background-color: #d58f34;
był tam primary, nie wiem czeu się zmienił :)

2023-05-31 13:58 UTC, Stolkens commented on src/redux/cartRedux.js
> +          products: [...statePart.products, { ...action.payload, quantity: 1 }],
hmmm może masz rację, a myślisz, że jest minus takiego rozwiązania?

2023-05-31 20:01 UTC, LukaszLewandowski91 commented on src/redux/cartRedux.js
> +          products: [...statePart.products, { ...action.payload, quantity: 1 }],
Wydaje mi się, że Twoje rozwiązanie z trzymaniem ilości koszyka w products może spowodować, że jak uruchomimy aplikcję na serwerze to będzie zamieszanie. Przykładowo klient X doda produkt A do koszyka, spowoduje to dodanie ilości do produktu, klient Y również doda produkt A do koszyka to automatycznie w koszyku wyświetli mu 2 szt. zarówno to co kliknął klient X jak i klient Y.
Mam nadzieję, ze jasno opisałem

2023-06-01 10:14 UTC, LukaszLewandowski91 approved these changes

2023-06-01 11:52 UTC, merged