[WDP230501-45] Fix bugs on HomePage
matwjablonski/wdp-2305-01 pull request #62
Opened 2023-06-01 11:49 UTC by Stolkens

- zmiana ta naglowkow
- zmiana koloru HotDeals
- wyrownanie wszyskich sekcji
- pozycjonowanie opisu w sekcji sales
- ustawienie pointera na kropkach i usuniecie "dziwnych" kresek obok nich
- zmiana koloru starej ceny

https://projects.kodilla.com/browse/WDP230501-45

2023-06-01 12:36 UTC, LukaszLewandowski91 requested changes
Mobilna/tabletowa wersja galleryBox się posypała ;)

2023-06-01 13:07 UTC, Stolkens commented
> Mobilna/tabletowa wersja galleryBox się posypała ;)

teraz powinno byc ok

2023-06-02 04:36 UTC, LukaszLewandowski91 approved these changes

2023-06-02 05:57 UTC, matwjablonski approved these changes

2023-06-02 05:57 UTC, merged