change scss, new branch
matwjablonski/wdp-2305-01 pull request #63
Opened 2023-06-01 16:56 UTC by JL9696

-ustawienie trzech boxów w kolejności: pierwszy największy, a reszta niżej.
-dodanie zmian w scss

https://projects.kodilla.com/browse/WDP230501-26

2023-06-01 18:33 UTC, Stolkens reviewed
Mysle, ze wyglada spoko jedynie mozna by zmniejszyc odleglosc miedzy pierwszym zdjeciem a drugim, i wyrownac pierwsze zdjecie na szerokosc z tymi dwoma pod spodem zeby byly tej samej szerokosci 
![image](https://github.com/matwjablonski/wdp-2305-01/assets/92957952/7bb48e7a-5ca2-4a69-aeab-d348c737310e)

2023-06-01 19:46 UTC, LukaszLewandowski91 requested changes
Jedna uwaga i będzie super :)

2023-06-01 19:46 UTC, LukaszLewandowski91 commented on src/components/features/Sales/Sales.module.scss
> +    margin-bottom: 70px;
margin-bottom usuń a zamiast tego daj width: 100% - to powinno wyrównać górny box do dolnych :)

2023-06-02 07:02 UTC, monte-dev requested changes
Kilka drobnych rzeczy + to co napisali inni a tak to dobra robota :)

2023-06-02 07:02 UTC, monte-dev commented on src/components/features/Sales/Sales.module.scss
> +  .bottom {
Przydalyby sie odstepy pomiedzy regulami tak jak w niektorych miejsach (czytelność kodu)

2023-06-04 19:08 UTC, LukaszLewandowski91 approved these changes

2023-06-05 06:06 UTC, Stolkens approved these changes

2023-06-05 07:55 UTC, monte-dev approved these changes

2023-06-05 08:06 UTC, matwjablonski approved these changes

2023-06-05 08:12 UTC, merged