Wdp230501 38 add cart local storage
matwjablonski/wdp-2305-01 pull request #66
Opened 2023-06-03 21:35 UTC by DawSeg

2023-06-04 07:11 UTC, LukaszLewandowski91 requested changes
Po przejściu z zakładki HOME na dowolną inną koszyk nie wyświetla wcześniej dodanych produktów.
![image](https://github.com/matwjablonski/wdp-2305-01/assets/119667464/2517f1fc-ded6-4b86-9430-00f548992d43)

2023-06-05 07:28 UTC, Stolkens requested changes
Proponowałbym dodać jeszcze do Cart możliwość usunięcia rzeczy z koszyka - wszystko masz w moim poprzednim PR dotyczącym tego zadania (wystarczy przekopiować razem ze stylami i akcją clearCart z CartRedux)

2023-06-05 07:28 UTC, Stolkens commented on src/components/features/NewFurniture/NewFurniture.js
> +  }, [dispatch]);
Przerzuć cały ten blok  useEffect do ProductBox i będzie działać na innych podstronach też.

2023-06-05 07:28 UTC, Stolkens commented on src/components/features/Promoted/PromotedProducts.js
>    //}
usuń zakomentowany kod

2023-06-05 07:28 UTC, Stolkens commented on src/components/features/Promoted/PromotedProducts.js
> +      // }
tutaj też

2023-06-05 07:28 UTC, Stolkens commented on src/components/features/Promoted/PromotedProducts.js
>                  <FontAwesomeIcon icon={faCircle} className={dotStyles[2]} />
j.w.

2023-06-05 07:36 UTC, Stolkens commented on src/components/features/NewFurniture/NewFurniture.js
> +  }, [dispatch]);
dobra miałem chwilę więc ogarnąłem :)

2023-06-05 08:08 UTC, monte-dev approved these changes

2023-06-05 09:36 UTC, Stolkens reviewed
Wróciłem do poprzedniej wersji bo moja też miała błąd....poprawiłem małe błędy ale koszyk nadal resetuje się przy zmianie podstron

2023-06-05 13:49 UTC, LukaszLewandowski91 commented
Ogólnie koszyk działa ale cały Promoted się ponownie rozjeżdża - prawdopodobnie konflikty zostały źle rozwiązane

2023-06-05 15:09 UTC, LukaszLewandowski91 approved these changes

2023-06-05 16:02 UTC, merged