Add old price and display sale(new) price in ProductBox
matwjablonski/wdp-2305-01 pull request #7
Opened 2023-05-17 18:34 UTC by monte-dev

[jira task](https://projects.kodilla.com/browse/WDP230501-6)

2023-05-18 07:18 UTC, LukaszLewandowski91 approved these changes

2023-05-18 18:26 UTC, DawSeg approved these changes

2023-05-19 14:24 UTC, matwjablonski requested changes

2023-05-19 18:35 UTC, monte-dev commented on src/components/common/ProductBox/ProductBox.module.scss
> +      color: #c8c8c8;
Okej, już zrobione

2023-05-22 08:12 UTC, matwjablonski commented
@monte-dev są konflikty

2023-05-23 07:28 UTC, matwjablonski commented
nadal nie rozwiązane konflikty - poproś kogoś z zespołu o pomoc w rozwiązaniu bo widać nie wyrównałeś poprawnie branchy

2023-05-23 09:29 UTC, monte-dev commented
> [<img alt="@monte-dev" width="20" height="20" src="https://avatars.githubusercontent.com/u/119732972?s=40&amp;v=4"> ](/monte-dev)
> ` [Merge branch 'main' into WDP230501-6](/matwjablonski/wdp-2305-01/pull/7/commits/87523452be865d807b4437cdc119fc9ad3c48804) `
> Verified
> ` [8752345](/matwjablonski/wdp-2305-01/pull/7/commits/87523452be865d807b4437cdc119fc9ad3c48804)`

gotowe, Łukasz pomógł :)

2023-05-25 09:18 UTC, matwjablonski approved these changes

2023-05-25 09:18 UTC, merged